import { Roboto } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/shared/sidebar";

const roboto = Roboto({ subsets: ["latin"], weight: ["100", "300", "400", "500", "700"], });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="min-h-screen flex flex-auto flex-shrink-0 antialiased bg-white text-gray-800">
          <Sidebar />
          <div className="w-full bg-slate-200">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
