const animals = [
  {
    name: "Bongo",
    image: "/src/assets/animalsImages/bongoo.png",
    type: "Dog",
    race: "Golden Retriever",
    gender: "Male",
    age: "2 years",
    color: "Golden",
    location: "Bucharest",
  },
  {
    name: "Roblet",
    image: "/src/assets/animalsImages/roblet.png",
    type: "Dog",
    race: "Pug",
    gender: "Male",
    age: "2 years",
    color: "Brown",
    location: "Lucknow",
  },
  {
    name: "Sipper",
    image: "/src/assets/animalsImages/sipper.png",
    type: "Dog",
    race: "Husky",
    gender: "Male",
    age: "6 years",
    color: "Brown and white",
    location: "Mogi das Cruzes",
  },
  {
    name: "Russia",
    image: "/src/assets/animalsImages/russia.png",
    type: "Cat",
    race: "Persian",
    gender: "Female",
    age: "2.5 years",
    color: "White",
    location: "Manchester",
  },
  {
    name: "Mia",
    image: "/src/assets/animalsImages/mia.png",
    type: "Rabit",
    race: "Rabbit",
    gender: "Female",
    age: "1 year",
    color: "White",
    location: "Bucharest",
  },
  {
    name: "Zombo",
    image: "/src/assets/animalsImages/cat.png",
    type: "Cat",
    race: "Persian",
    gender: "Female",
    age: "3 years",
    color: "White",
    location: "Bucharest",
  },
]

export default animals
